### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by davipatricio** [davipatricio/arthurita#2]
- [ ] Server
  - [ ] Send chunks to Player on connect
  - [ ] Compression
  - [ ] Receive Player chats
  - [ ] Receive Player commands
  - [ ] Player methods
    - [ ] `kick(message)`
    - [ ] `sendTitle(options)`
    - [ ] `setHealth(health)`
    - [ ] `setHunger(food)`
    - [ ] `setFoodSaturation(saturation)`
  - [ ] Commands

**Future packages**
- [ ] @arthurita/nbt
  - [ ] Write and parse datatypes from buffer without `@arthurita/encoding` (because most datatypes are big-endian) (https://wiki.vg/NBT#Specification)
  - [ ] Read and parse a NBT from a buffer (`nbt.parse(await readFile('./servers.dat'))`)
  - [ ] Write a NBT from a object (something like `nbt.write({ type: 'compound', name: 'example' })`)
